// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBa-p2n8vaRIogJCVVoGDjYNP4tpt7gDoM',
    appId: '1:256955403295:web:bf067896c91518a5cb992a',
    messagingSenderId: '256955403295',
    projectId: 'banja22',
    authDomain: 'banja22.firebaseapp.com',
    storageBucket: 'banja22.appspot.com',
    measurementId: 'G-QF7PJB3P7K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA21jcSid25OKYcSKsAOe4lB9RYv-CMxG0',
    appId: '1:256955403295:android:bab21014ea022671cb992a',
    messagingSenderId: '256955403295',
    projectId: 'banja22',
    storageBucket: 'banja22.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOKtn0MbU7HTDcdu8FQ5VgfYG5Fv9Tw6E',
    appId: '1:256955403295:ios:2652b3b7a177823bcb992a',
    messagingSenderId: '256955403295',
    projectId: 'banja22',
    storageBucket: 'banja22.appspot.com',
    androidClientId: '256955403295-hks4ame3v9a02jg1cvseemv6mfr2ilqf.apps.googleusercontent.com',
    iosClientId: '256955403295-8a4pq004a6h1p8kr60q0jlbjcqc8rm93.apps.googleusercontent.com',
    iosBundleId: 'com.example.banja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOKtn0MbU7HTDcdu8FQ5VgfYG5Fv9Tw6E',
    appId: '1:256955403295:ios:2652b3b7a177823bcb992a',
    messagingSenderId: '256955403295',
    projectId: 'banja22',
    storageBucket: 'banja22.appspot.com',
    androidClientId: '256955403295-hks4ame3v9a02jg1cvseemv6mfr2ilqf.apps.googleusercontent.com',
    iosClientId: '256955403295-8a4pq004a6h1p8kr60q0jlbjcqc8rm93.apps.googleusercontent.com',
    iosBundleId: 'com.example.banja',
  );
}
